name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world-python:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
 # Add the Azure login step
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to Azure Container Instances
      uses: Azure/aci-deploy@v1
      with:
    # Name of the Resource Group in which the Container Instance will be created
        resource-group: "LEARN" 
        name: "pythonhelloworld"       
        ports: 80
        registry-login-server: ${{ secrets.DOCKERHUB_REPOSITORY }}
    # Username to log in Container Image Registry Server
        registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
        registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
    # Restart Policy for the container(s). Accepted Values are { Always, OnFailure, Never }
     
    # List of secure environment variables for the container. Space seperated values in "key=value" format
    
